spring:
  liquibase:
    enabled: true
    change-log: classpath:liquibaseRoot.xml
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:65432/security-test
    username: admin
    password: admin
  jpa:
    show-sql: true
